-- PROD : PRODUCT (상품)   

CREATE TABLE PRODUCT_ORDER
(
	PROD_SEQ               INT AUTO_INCREMENT,
	PROD_BARCODE		   VARCHAR(100) PRIMARY KEY NOT NULL,
	PROD_ORDER_NAME    	   VARCHAR(100) NOT NULL,
	PROD_PHONENUMBER	   VARCHAR(100) NOT NULL,
	PROD_SAVE_DATETIME	   datetime,
	PROD_USE_DATETIME	   datetime,
	PROD_PROPRIETARY_NAME  VARCHAR(100) NOT NULL,
	PROD_PROPRIETARY_PRICE VARCHAR(100) NOT NULL,
	PROD_TEXT  			   TEXT,
	PROD_USE			   VARCHAR(1) NOT NULL,
	KEY(PROD_SEQ)
)
;
INSERT INTO PRODUCT_ORDER 
	(
		PROD_BARCODE,
		PROD_ORDER_NAME,
		PROD_PHONENUMBER,
		PROD_SAVE_DATETIME,
		PROD_PROPRIETARY_NAME,
		PROD_PROPRIETARY_PRICE,
		PROD_TEXT,
		PROD_USE
	)
		VALUES
	(
		'111222333444',
		'송희윤',
		'01030490450',
		NOW(),
		'딸기생크림케이크4호',
		'27000',
		'본인수령이 아닙니다. 생축하 글씨를 써주세요.',
		'0'
	);
	
CREATE TABLE STOREDATA
(
	STORE_NAME		   	    VARCHAR(100) NOT NULL,
	STORE_PHONENUMBER    	VARCHAR(100) NOT NULL,
	STORE_JUSO_O	   	    VARCHAR(100) NOT NULL,
	STORE_JUSO_N	        VARCHAR(100) NOT NULL, 
	STORE_MAP_POINT	 	    VARCHAR(100) NOT NULL,
	STORE_URL  				VARCHAR(100) NOT NULL
)
;
INSERT INTO STOREDATA 
	(
		STORE_NAME		   	    ,
		STORE_PHONENUMBER    	,
		STORE_JUSO_O	   	    ,
		STORE_JUSO_N	        , 
		STORE_MAP_POINT	 	    ,
		STORE_URL  				
	)
		VALUES
	(
		'화곡2동',
		'070-8884-0450',
		'서울특별시 강서구 화곡4동 837-12호 1층 뚜레쥬르',
		'서울특별시 강서구 곰달래로 49길 10 뚜레쥬르 (화곡동)',
		'37.5321742/126.85802609999996',
		'http://192.168.219.6:8080/tlj_mobil/couponsel.do?bar='
	);
	
CREATE TABLE PRODUCT_LIST(
	PROD_NAME VARCHAR(50) PRIMARY KEY NOT NULL,
	PROD_TYPE VARCHAR(1) NOT NULL,
	PROD_IMGNAME VARCHAR(50) NULL
);

INSERT INTO PRODUCT_LIST VALUES('생크림케이크1호','A','A001.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림케이크2호','A','A002.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림케이크3호','A','A003.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림케이크4호','A','A004.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림케이크5호','A','A005.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림케이크6호','A','A006.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코생크림1호','A','A007.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코생크림2호','A','A008.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코생크림3호','A','A009.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코생크림4호','A','A010.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코생크림5호','A','A011.jpg');
INSERT INTO PRODUCT_LIST VALUES('순매직베리케이크','A','A012.jpg');
INSERT INTO PRODUCT_LIST VALUES('순매직딸기케이크','A','A013.jpg');
INSERT INTO PRODUCT_LIST VALUES('순블루베리쉬폰1호','A','A014.jpg');
INSERT INTO PRODUCT_LIST VALUES('순블루베리쉬폰2호','A','A015.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림을사랑한폴리','A','A016.jpg');
INSERT INTO PRODUCT_LIST VALUES('생크림구름위에폴리와헬리','A','A017.jpg');
INSERT INTO PRODUCT_LIST VALUES('달콤초코쉬폰1호','A','A018.jpg');
INSERT INTO PRODUCT_LIST VALUES('달콤초코쉬폰2호','A','A019.jpg');
INSERT INTO PRODUCT_LIST VALUES('블루베리하트케이크2호','A','A020.jpg');

INSERT INTO PRODUCT_LIST VALUES('클래식치즈케이크','B','B001.jpg');
INSERT INTO PRODUCT_LIST VALUES('자연치즈가 들어간 순치즈케이크','B','B002.jpg');
INSERT INTO PRODUCT_LIST VALUES('고구마티라미스를만나다','B','B003.jpg');
INSERT INTO PRODUCT_LIST VALUES('순꿀치즈케이크','B','B004.jpg');
INSERT INTO PRODUCT_LIST VALUES('티라미슈','B','B005.jpg');
INSERT INTO PRODUCT_LIST VALUES('상큼블루베리치즈무스','B','B006.jpg');
INSERT INTO PRODUCT_LIST VALUES('까망쿠키까망베르치즈케이크','B','B007.jpg');
INSERT INTO PRODUCT_LIST VALUES('떠먹는블루베리요거트케이크','B','B008.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴트리플치즈케이크','B','B009.jpg');
INSERT INTO PRODUCT_LIST VALUES('케이크속에순우유','B','B010.jpg');
INSERT INTO PRODUCT_LIST VALUES('딸기티라미슈','B','B011.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴고구마케이크1호','B','B012.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴고구마케이크2호','B','B013.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴고구마케이크3호','B','B014.jpg');

INSERT INTO PRODUCT_LIST VALUES('버크섬수호자드래곤','C','C001.jpg');
INSERT INTO PRODUCT_LIST VALUES('스위트초코볼케이크','C','C002.jpg');
INSERT INTO PRODUCT_LIST VALUES('로맨틱홀리데이','C','C003.jpg');
INSERT INTO PRODUCT_LIST VALUES('쎄시봉케이크','C','C004.jpg');
INSERT INTO PRODUCT_LIST VALUES('스위트매직캐슬','C','C005.jpg');
INSERT INTO PRODUCT_LIST VALUES('라바의뉴욕여행기','C','C006.jpg');
INSERT INTO PRODUCT_LIST VALUES('라바의뮤직콘서트','C','C007.jpg');
INSERT INTO PRODUCT_LIST VALUES('순~양케이크','C','C008.jpg');
INSERT INTO PRODUCT_LIST VALUES('까망쿠키라바월드','C','C009.jpg');
INSERT INTO PRODUCT_LIST VALUES('클래식녹차케이크','C','C010.jpg');
INSERT INTO PRODUCT_LIST VALUES('꿀벌왕국순꿀대소동','C','C011.jpg');
INSERT INTO PRODUCT_LIST VALUES('달콤밀크초코케익4호','C','C012.jpg');
INSERT INTO PRODUCT_LIST VALUES('리치카페','C','C013.jpg');
INSERT INTO PRODUCT_LIST VALUES('쿵푸팬더케이크','C','C014.jpg');
INSERT INTO PRODUCT_LIST VALUES('라바가 축하해주는 생일파티','C','C015.jpg');
INSERT INTO PRODUCT_LIST VALUES('출동!헬리의구조작전','C','C016.jpg');
INSERT INTO PRODUCT_LIST VALUES('라바의초코통나무','C','C017.jpg');
INSERT INTO PRODUCT_LIST VALUES('진한초코케이크','C','C018.jpg');
INSERT INTO PRODUCT_LIST VALUES('러브초코돔마블케이크','C','C019.jpg');
INSERT INTO PRODUCT_LIST VALUES('TLJ호두아몬드케이크','C','C020.jpg');
INSERT INTO PRODUCT_LIST VALUES('라바의 초코볼 대소동','C','C021.jpg');
INSERT INTO PRODUCT_LIST VALUES('폴리와엠버의스마트케이크','C','C022.jpg');
INSERT INTO PRODUCT_LIST VALUES('출동!로보카폴리와친구들','C','C023.jpg');
INSERT INTO PRODUCT_LIST VALUES('헬리!생일을축하해','C','C024.jpg');
INSERT INTO PRODUCT_LIST VALUES('러블리엠버2호','C','C025.jpg');
INSERT INTO PRODUCT_LIST VALUES('달콤세레나데','C','C026.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴욕시티레드벨벳','C','C027.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴프리미엄쇼콜라케익2호','C','C028.jpg');
INSERT INTO PRODUCT_LIST VALUES('초콜릿가득부드러운모카케익3호','C','C029.jpg');
INSERT INTO PRODUCT_LIST VALUES('다크초코스퀘어','C','C030.jpg');
INSERT INTO PRODUCT_LIST VALUES('뉴오페라케이크','C','C031.jpg');
INSERT INTO PRODUCT_LIST VALUES('클래식모카케익','C','C032.jpg');
INSERT INTO PRODUCT_LIST VALUES('우리쌀케익','C','C033.jpg');
INSERT INTO PRODUCT_LIST VALUES('초콜릿가득부드러운모카케익','C','C034.jpg');
INSERT INTO PRODUCT_LIST VALUES('커피향은은한모카케익','C','C035.jpg');
INSERT INTO PRODUCT_LIST VALUES('곰돌이와함께하는파티케이크','C','C036.jpg');
INSERT INTO PRODUCT_LIST VALUES('카페플라워','C','C037.jpg');
INSERT INTO PRODUCT_LIST VALUES('쇼콜라봉봉','C','C038.jpg');
INSERT INTO PRODUCT_LIST VALUES('사랑에빠진쇼콜라','C','C039.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코더클래식','C','C040.jpg');
INSERT INTO PRODUCT_LIST VALUES('사랑을전하는가나슈케익','C','C041.jpg');
INSERT INTO PRODUCT_LIST VALUES('하트를듬뿍담은쇼콜라스퀘어','C','C042.jpg');
INSERT INTO PRODUCT_LIST VALUES('천사가전하는상큼스트로베리케익','C','C043.jpg');
INSERT INTO PRODUCT_LIST VALUES('프로포즈하트케익1호','C','C044.jpg');
INSERT INTO PRODUCT_LIST VALUES('러브블루베리케이크','C','C045.jpg');
INSERT INTO PRODUCT_LIST VALUES('프리미엄녹차케익(대)','C','C046.jpg');
INSERT INTO PRODUCT_LIST VALUES('달콤화이트초코케익3호','C','C047.jpg');
INSERT INTO PRODUCT_LIST VALUES('초코패밀리케익5호','C','C048.jpg');
INSERT INTO PRODUCT_LIST VALUES('화이트스퀘어케익','C','C049.jpg');
INSERT INTO PRODUCT_LIST VALUES('드림포코하트케익','C','C050.jpg');
INSERT INTO PRODUCT_LIST VALUES('블루베리크림케이크1호','C','C051.jpg');
INSERT INTO PRODUCT_LIST VALUES('스트로베리크림하트케이크','C','C052.jpg');
INSERT INTO PRODUCT_LIST VALUES('리치쇼콜라케이크1호','C','C053.jpg');
INSERT INTO PRODUCT_LIST VALUES('키스스트로베리 크림케이크','C','C054.jpg');
