-- PROD : PRODUCT (상품)   

CREATE TABLE PRODUCT_ORDER
(
	PROD_SEQ               INT AUTO_INCREMENT,
	PROD_BARCODE		   VARCHAR(100) PRIMARY KEY NOT NULL,
	PROD_ORDER_NAME    	   VARCHAR(100) NOT NULL,
	PROD_PHONENUMBER	   VARCHAR(100) NOT NULL,
	PROD_SAVE_DATETIME	   datetime,
	PROD_USE_DATETIME	   datetime,
	PROD_PROPRIETARY_NAME  VARCHAR(100) NOT NULL,
	PROD_PROPRIETARY_PRICE VARCHAR(100) NOT NULL,
	PROD_TEXT  			   TEXT,
	PROD_USE			   VARCHAR(1) NOT NULL,
	KEY(PROD_SEQ)
)
;
INSERT INTO PRODUCT_ORDER 
	(
		PROD_BARCODE,
		PROD_ORDER_NAME,
		PROD_PHONENUMBER,
		PROD_SAVE_DATETIME,
		PROD_PROPRIETARY_NAME,
		PROD_PROPRIETARY_PRICE,
		PROD_TEXT,
		PROD_USE
	)
		VALUES
	(
		'111222333444',
		'송희윤',
		'01030490450',
		NOW(),
		'딸기생크림케이크4호',
		'27000',
		'본인수령이 아닙니다. 생축하 글씨를 써주세요.',
		'0'
	);
	
CREATE TABLE STOREDATA
(
	STORE_NAME		   	    VARCHAR(100) NOT NULL,
	STORE_PHONENUMBER    	VARCHAR(100) NOT NULL,
	STORE_JUSO_O	   	    VARCHAR(100) NOT NULL,
	STORE_JUSO_N	        VARCHAR(100) NOT NULL, 
	STORE_MAP_POINT	 	    VARCHAR(100) NOT NULL,
	STORE_URL  				VARCHAR(100) NOT NULL
)
;
INSERT INTO STOREDATA 
	(
		STORE_NAME		   	    ,
		STORE_PHONENUMBER    	,
		STORE_JUSO_O	   	    ,
		STORE_JUSO_N	        , 
		STORE_MAP_POINT	 	    ,
		STORE_URL  				
	)
		VALUES
	(
		'화곡2동',
		'070-8884-0450',
		'서울특별시 강서구 화곡4동 837-12호 1층 뚜레쥬르',
		'서울특별시 강서구 곰달래로 49길 10 뚜레쥬르 (화곡동)',
		'37.5321742/126.85802609999996',
		'http://192.168.219.6:8080/tlj_mobil/couponsel.do?bar='
	);